base/urls.py
from django.urls import path

from base import views

app_name = 'base'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('services/', views.ServicesView.as_view(), name='services'),
    path('about/', views.AboutView.as_view(), name='about'),
]

users/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView, TokenVerifyView)

from users import views

app_name = 'users'
user_api_router = SimpleRouter()
user_api_router.register(
    'api',
    views.UserAPIViewSet,
    basename='user-api',
)

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('login_create/', views.UserLoginCreateView.as_view(),
         name='login_create'),
    path('dashboard/', views.UserDashboardView.as_view(), name='dashboard'),
    path('dashboard/update/', views.UserUpdateView.as_view(), name='update'),
    path('dashboard/update/password/',
         views.PasswordUpdateView.as_view(), name='change_password'),
    path('dashboard/appointment/<int:pk>/',
         views.AppointmentDetailView.as_view(),
         name='appointment_detail'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('clear/', views.ClearSessionView.as_view(), name='clear'),
    path('delete/', views.DashboardAppointmentDelete.as_view(),
         name='appointment_delete'),
    path('api/token/',
         TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/',
         TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/',
         TokenVerifyView.as_view(), name='token_verify'),
]

urlpatterns += user_api_router.urls

users/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=14, unique=True)
    phone_number = models.CharField(max_length=20)

users/forms/login.py
from django import forms
from django.utils.translation import gettext_lazy as _

from utils.django_forms import add_placeholder


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], _('Enter your username'))
        add_placeholder(self.fields['password'], _('Enter your password'))

    username = forms.CharField(label=_('Username'))
    password = forms.CharField(
        widget=forms.PasswordInput(), label=_('Password'))

schedule/views/appointment_views.py
import datetime as dt

from django.http import JsonResponse
from django.urls import reverse
from django.views import View

from schedule.models import Appointment


class AvailableAppointmentTimes(View):
    def get(self, request):
        selected_date = request.GET.get('date')
        booked_appointments = Appointment.objects.filter(
            date=selected_date).values_list('time', flat=True)
        booked_appointments = [apt.strftime('%H:%M')
                               for apt in booked_appointments]
        all_times = [f'{i:02d}:00' for i in range(8, 18)]
        available_times = [
            time for time in all_times if time not in booked_appointments
        ]
        return JsonResponse({'available_times': available_times})

    def get_url(self):
        return reverse('schedule:times')


class AvailableAppointmentDates(View):
    def get(self, request):
        selected_time = request.GET.get('time')
        booked_appointments = Appointment.objects.filter(
            time=selected_time).values_list('date', flat=True)
        today = dt.date.today()
        all_dates = [
            d.isoformat() for i in range(1, 61)
            if (d := (today + dt.timedelta(days=i))).weekday() != 6
        ]
        available_dates = [
            (date, dt.datetime.strptime(date, '%Y-%m-%d').strftime('%d-%m-%Y'))
            for date in all_dates if date not in booked_appointments
        ]
        return JsonResponse({'available_dates': available_dates})

    def get_url(self):
        return reverse('schedule:dates')

users/views/api.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.exceptions import PermissionDenied
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from users.serializers import UserSerializer


class UserAPIViewSet(ModelViewSet):
    serializer_class = UserSerializer
    permission_classes = [IsAuthenticated, ]
    http_method_names = ['get', 'post', 'patch']

    def get_queryset(self):
        User = get_user_model()
        if self.request.user.is_staff:
            return User.objects.all()
        return User.objects.filter(username=self.request.user.username)

    def get_object(self):
        pk = self.kwargs.get('pk', '')
        obj = get_object_or_404(
            self.get_queryset(),
            pk=pk,
        )
        return obj

    @action(
        methods=['get'],
        detail=False,
    )
    def me(self, request, *args, **kwargs):
        obj = self.get_queryset().first()
        serializer = self.get_serializer(
            instance=obj,
        )
        return Response(serializer.data)

    def create(self, request, *args, **kwargs):
        serializer = UserSerializer(
            data=request.data,
            context={'request': request}
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)

    def partial_update(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj != request.user and not request.user.is_staff:
            raise PermissionDenied(
                'You do not have permission to update this user.')
        serializer = UserSerializer(
            instance=obj,
            data=request.data,
            context={'request': request},
            partial=True,
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

users/views/dashboard.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from django.views import View
from django.views.generic import DetailView

from schedule.models import Appointment


class UserDashboardView(LoginRequiredMixin, View):
    login_url = 'users:login'
    redirect_field_name = 'next'

    def get_appointment(self, id=None):
        appointment = None
        if id:
            appointment = Appointment.objects.filter(
                is_completed=False,
                user=self.request.user,
                id=id,
            ).first()
            if not appointment:
                raise Http404()
        return appointment

    def get(self, request):
        appointments = Appointment.objects.select_related(
            'user', 'procedure'
        ).filter(
            user=request.user, is_completed=False
        ).order_by('date', 'time')
        closed_appointments = Appointment.objects.select_related(
            'user', 'procedure'
        ).filter(
            user=request.user, is_completed=True
        ).order_by('date', 'time')
        context = {
            'appointments': appointments,
            'closed_appointments': closed_appointments,
        }
        return render(request, 'users/pages/dashboard.html', context=context)


@method_decorator(
    login_required(login_url='users:login', redirect_field_name='next'),
    name='dispatch'
)
class DashboardAppointmentDelete(UserDashboardView):
    def post(self, *args, **kwargs):
        appointment = self.get_appointment(self.request.POST.get('id'))
        appointment.delete()
        messages.success(self.request, _('Appointment successfully canceled'))
        return redirect(reverse('users:dashboard'))


class AppointmentDetailView(DetailView):
    model = Appointment
    context_object_name = 'appointment'
    template_name = 'users/pages/appointment.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(user=self.request.user)
        return queryset

users/views/login.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import View

from users.forms import LoginForm


class UserLoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect(reverse('users:dashboard'))
        form = LoginForm()
        context = {
            'form': form,
            'form_action': reverse('users:login_create'),
        }
        return render(request, 'users/pages/login.html', context=context)


class UserLoginCreateView(View):
    def get(self, request):
        raise Http404()

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            authenticated_user = authenticate(
                username=form.cleaned_data.get('username', ''),
                password=form.cleaned_data.get('password', ''),
            )
            if authenticated_user:
                messages.success(request, _('You are logged in'))
                login(request, authenticated_user)
            else:
                messages.error(request, _('Invalid credentials'))
        else:
            messages.error(request, _('Invalid username or password'))
        return redirect(reverse('users:dashboard'))

users/views/logout.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import View


class UserLogoutView(LoginRequiredMixin, View):
    login_url = 'users:login'
    redirect_field_name = 'next'

    def get(self, request):
        messages.error(request, _('Invalid logout request'))
        return redirect(reverse('users:login'))

    def post(self, request):
        if request.POST.get('username') != request.user.username:
            messages.error(request, _('Invalid logout user'))
        else:
            logout(request)
            messages.success(request, _('Logged out successfully'))
        return redirect(reverse('users:login'))

users/views/register.py
from django.contrib import messages
from django.http import Http404, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import View

from users.forms import RegisterForm
from users.models import Profile


class UserRegisterView(View):
    template_name = 'users/pages/register.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect(reverse('users:dashboard'))
        register_form_data = request.session.get('register_form_data')
        form = RegisterForm(register_form_data)
        context = {
            'form': form,
            'form_action': reverse('users:create'),
        }
        return render(
            request, self.template_name, context=context
        )


class UserCreateView(View):
    def get(self, request):
        raise Http404()

    def post(self, request):
        POST = request.POST
        request.session['register_form_data'] = POST
        form = RegisterForm(POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            profile = Profile.objects.create(
                user=user,
                cpf=form.cleaned_data['cpf'],
                phone_number=form.cleaned_data.get('phone_number', 0),
            )
            profile.save()
            user_created = _(
                'User has been created, please log in'
            )
            messages.success(request, user_created)
            del request.session['register_form_data']
            return redirect(reverse('users:login'))
        return redirect('users:register')


class ClearSessionView(View):
    http_method_names = ['post']

    def get(self, request):
        raise Http404()

    def post(self, request):
        if 'register_form_data' in request.session:
            del request.session['register_form_data']
        return JsonResponse({'success': True})

users/views/update.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from django.views import View

from users.forms import ChangePasswordForm, UpdateForm


@method_decorator(
    login_required(login_url='users:login', redirect_field_name='next'),
    name='dispatch'
)
class UserUpdateView(View):
    template_name = 'users/pages/update.html'

    def get(self, request):
        form = UpdateForm(instance=request.user)
        context = {
            'form': form,
            'form_action': reverse('users:update'),
            'update': True,
        }
        return render(request, self.template_name, context=context)

    def get_updated_data(self, user, data):
        for key in data:
            if isinstance(data[key], list):
                data[key] = data[key][0]
        profile = data.get('profile', {})
        phone_number = profile.get('phone_number', user.profile.phone_number)
        return {
            'username': data.get('username', user.username),
            'password': data.get('password', user.password),
            'password2': data.get('password2', user.password),
            'email': data.get('email', user.email),
            'first_name': data.get('first_name', user.first_name),
            'last_name': data.get('last_name', user.last_name),
            'cpf': user.profile.cpf,
            'phone_number': phone_number,
        }

    def post(self, request):
        POST = request.POST
        form_data = self.get_updated_data(request.user, POST)
        form = UpdateForm(form_data, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            request.user.profile.phone_number = form.cleaned_data.get(
                'phone_number', '')
            request.user.profile.save()
            user.save()
            user_updated = _('User information has been updated')
            messages.success(request, user_updated)
            return redirect(reverse('users:dashboard'))
        context = {
            'form': form,
            'form_action': reverse('users:update'),
        }
        return render(request, self.template_name, context=context)


@method_decorator(
    login_required(login_url='users:login', redirect_field_name='next'),
    name='dispatch'
)
class PasswordUpdateView(View):
    template_name = 'users/pages/change_password.html'

    def get(self, request):
        form = ChangePasswordForm()
        context = {
            'form': form,
            'form_action': reverse('users:change_password'),
        }
        return render(request, self.template_name, context=context)

    def post(self, request):
        POST = request.POST
        form = ChangePasswordForm(POST)
        if form.is_valid():
            request.user.set_password(form.cleaned_data.get('password'))
            request.user.save()
            user_updated = _('Password has been changed successfully')
            messages.success(request, user_updated)
            return redirect(reverse('users:dashboard'))
        context = {
            'form': form,
            'form_action': reverse('users:change_password'),
        }
        return render(request, self.template_name, context=context)

users/templates/users/pages/appointment.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{{ appointment }}{% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        <div class="appointment appointment-list-item">
            <div class="appointment-title-container">
                <h2 class="appointment-title center">
                    {{ appointment }}
                </h2>
            </div>
            <div class="appointment-user">
                <span>
                    <h2><i class="fas fa-user"></i> {% translate "User" %}</h2>
                    {% if appointment.user %}
                        {% if appointment.user.first_name %}
                            {{ appointment.user.first_name }} {{ appointment.user.last_name }}
                        {% else %}
                            {{ appointment.user.username }}
                        {% endif %}
                    {% endif %}
                </span>
                <span>
                    <h2><i class="fas fa-layer-group"></i> {% translate "Procedure" %}</h2>
                    {{ appointment.procedure }}
                </span>
                <span>
                    <h2><i class="fas fa-calendar-alt"></i> {% translate "Appointment date and time" %}</h2>
                    {{ appointment.date|date:"d/m/Y" }} {% translate 'at' %} {{ appointment.time|date:"H:i" }}
                </span>
                <span>
                    <h2><i class="fas fa-calendar-alt"></i> {% translate "Scheduled at" %}</h2>
                    {{ appointment.scheduled_at|date:"d/m/Y" }} {% translate 'at' %} {{ appointment.scheduled_at|date:"H:i" }}
                </span>
                <span>
                    <h2><i class="fas fa-calendar-alt"></i> {% translate "Updated at" %}</h2>
                    {{ appointment.updated_at|date:"d/m/Y" }} {% translate 'at' %} {{ appointment.updated_at|date:"H:i" }}
                </span>
                <span>
                    <h2><i class="fas fa-calendar-check"></i> {% translate "Appointment confirmed" %}</h2>
                    {% if appointment.is_confirmed %}
                        ✔️
                    {% else %}
                        ✖️
                    {% endif %}
                </span>
                <span>
                    <h2><i class="fas fa-check-double"></i> {% translate "Appointment completed" %}</h2>
                    {% if appointment.is_completed %}
                        ✔️
                    {% else %}
                        ✖️
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/pages/change_password.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Change Password' %}{% endblock title %}

{% block content %}
    <div class="main-content center container article">
        <h2 class="register-page">{% translate 'Change Password' %}</h2>
        {% include 'global/partials/messages.html' %}
        <div class="update-form-wrapper">
            {% include 'global/partials/form.html' %}
        </div>
    </div>
{% endblock content %}

users/templates/users/pages/dashboard.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Dashboard' %}{% endblock title %}

{% block content %}
    <div class="main-content dashboard center container article">
        {% include 'global/partials/messages.html' %}
        <div class="dashboard-tag center">
            <h2>{% translate 'Dashboard' %}</h2>
            <div class="dashboard-update">
                <h3><a href="{% url 'users:update' %}">{% translate "Update Profile" %}</a></h3>
            </div>
            <div class="appointment-list center">
                {% if appointments %}
                    <h4>{% translate 'Your Appointments' %}</h4>
                    <div class="table-wrapper">
                        <table>
                            <thead>
                                <tr>
                                    <th>{% translate 'ID' %}</th>
                                    <th>{% translate 'Procedure' %}</th>
                                    <th>{% translate 'Date' %}</th>
                                    <th>{% translate 'Time' %}</th>
                                    <th>{% translate 'Price' %}</th>
                                    <th>{% translate 'Confirmed' %}</th>
                                    <th>{% translate 'Cancel' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for appointment in appointments %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'users:appointment_detail' appointment.id %}">#{{ appointment.id }}</a>
                                        </td>
                                        <td>{{ appointment.procedure }}</td>
                                        <td>{{ appointment.date }}</td>
                                        <td>{{ appointment.time }}</td>
                                        <td>R${{ appointment.procedure.price }}</td>
                                        <td>
                                            {% if appointment.is_confirmed %}
                                                ✔️
                                            {% else %}
                                                ✖️
                                            {% endif %}
                                        </td>
                                        <td>                          
                                            <form class="inline-form form-delete" action="{% url 'users:appointment_delete' %}" method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="id" value="{{ appointment.id }}">
                                                <button class="delete-button" type="submit">❌</button>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <h3><p>{% translate 'You have no appointments scheduled' %}</p></h3>
                {% endif %}
            </div>
            <div class="appointment-list">
                {% if closed_appointments %}
                    <h4>{% translate 'Treatment History' %}</h4>
                    <div class="table-wrapper">
                        <table>
                            <thead>
                                <tr>
                                    <th>{% translate 'ID' %}</th>
                                    <th>{% translate 'Procedure' %}</th>
                                    <th>{% translate 'Date' %}</th>
                                    <th>{% translate 'Time' %}</th>
                                    <th>{% translate 'Price' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for appointment in closed_appointments %}
                                    <tr>
                                        <td><a href="{% url 'users:appointment_detail' appointment.id %}">#{{ appointment.id }}</a></td>
                                        <td>{{ appointment.procedure }}</td>
                                        <td>{{ appointment.date }}</td>
                                        <td>{{ appointment.time }}</td>
                                        <td>R${{ appointment.procedure.price }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        var currentLanguage = "{{ LANGUAGE_CODE }}";
    </script>
{% endblock content %}

users/templates/users/pages/login.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Login' %}{% endblock title %}

{% block content %}
    <div class="main-content center container article">
        <h2 class="login-page">{% translate 'Login' %}</h2>
        {% include 'global/partials/messages.html' %}
        {% if not user.is_authenticated %}
            <div class="login-form-wrapper">
                {% include 'global/partials/form.html' %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

users/templates/users/pages/register.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Register' %}{% endblock title %}

{% block content %}
    <div class="main-content center container article">
        <h2 class="register-page">{% translate 'Register' %}</h2>
        {% include 'global/partials/messages.html' %}
        {% if not user.is_authenticated %}
            <div class="register-form-wrapper">
                {% include 'global/partials/form.html' %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

users/templates/users/pages/update.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Update Profile' %}{% endblock title %}

{% block content %}
    <div class="main-content center container article">
        <h2 class="update-page">{% translate 'Update Profile' %}</h2>
        {% include 'global/partials/messages.html' %}
        <div class="update-form-wrapper">
            {% include 'global/partials/form.html' %}
        </div>
    </div>
{% endblock content %}